### ISSUE TITLE
Strings as parameters

### ISSUE THREAD

**Issue by bestander** [jrowny/brackets-snippets#10]
Hi, thanks for the great extension.

I use Jasmine for writing tests and this pattern is quite common

```
describe('PublishController should be awesome', function () {
  // cursor here 
}
```

I'd like to create brackets snippet like this:

```
{
 "trigger": "de",
 "usage": "de 'Should be awesome'",
 "template": "describe($${when}, function () {\n!!{cursor}\n}"
}
```

The result is undesirable

``` javascript
  de 'Should be awesome'
  describe('Should, function () {

             }
```

**Comment by jrowny** [comment]
This is a good idea.

**Comment by jrowny** [comment]
While I haven't got this working yet, if you omit the parameter altogether, you now get a nice inline for, which allows you to enter long strings with spaces.

**Comment by bestander** [comment]
Yep, thanks for the advice

**Comment by adalberth** [comment]
+1 for strings as parameters

**Comment by zaggino** [comment]
Fixed in https://github.com/jrowny/brackets-snippets/pull/33

**Comment by jrowny** [comment]
Merged
