### ISSUE TITLE
Error with .DS_Store

### ISSUE THREAD

**Issue by cfjedimaster** [jrowny/brackets-snippets#11]
If a .DS_Store file exists and the extension tries to read it, you get an error on startup.

**Comment by jrowny** [comment]
It's just a warning right? Things still work?

**Comment by cfjedimaster** [comment]
Yep, I can click past it.

**Comment by chrismatheson** [comment]
For me it broke things :( after i got the error i could continue and still use brackets but the plugin was not working from that point onwards. 

Ive done a small work around. I can try and wrangle this into a proper pull req if you want? or can just leave it for a temporary solution until you decide how you would like to solve the issue

``` javascript
define(function (require, exports, module) {
    function (entries) {
        var i, loading = [], len = entries.length;
            for (i = 0; i < len; i++) {
                if (entries[i].name.charAt(0) === ".") {
                    //ignore dotfiles
                    return
                }
                loading.push(loadSnippet(entries[i]));
             }
         $.when.apply(module, loading).done(finalizeSnippetsTable);
```

**Comment by jrowny** [comment]
A pull request would be much appreciated, but I wonder if we should "whitelist" file types rather than block certain ones. I.e., only allow .snippet and .json. Let me know if you want to try and tackle it, otherwise I'll try to find some time this weekend for it.

**Comment by jrowny** [comment]
Fixed thanks to @chrismatheson

**Comment by clouddueling** [comment]
Brackets 33 just came out and after updating brackets-snippets I edited one of my snippets and started getting this message.

![screen shot 2013-10-31 at 12 32 52 pm](https://f.cloud.github.com/assets/1400735/1449124/476bc6b0-4263-11e3-9f09-528a6a14d42b.png)

Chris's fix hides the error but now I can't use the extension.
Love this extension hope this can get fixed soon!

**Comment by jrowny** [comment]
I haven't booted up my mac in awhile and obviously don't get this on linux/windows. I'll see if I can get to it and I'll reopen the issue. In the meantime if someone has a pull, I'm happy to merge!

One last thing, did you download from the extension repository or from github?

**Comment by clouddueling** [comment]
@jrowny I downloaded from within brackets extension manager thing (extension repository?).

I can submit this as a pull request but I only used chris's method with the if statement.

**Comment by jrowny** [comment]
Can you clone this repo and tell me if you still get the error? I think the one in extension manager might be missing the latest fix. Chris' fix was later fixed again by @cfjedimaster and I'm not sure if that one was pushed out yet.

If that's the case then all I need to do is re-upload the latest code to the extension repository..

**Comment by clouddueling** [comment]
I just cloned and it worked fine.
https://github.com/jrowny/brackets-snippets/issues/22

This only happened because I added a php.json and then a .DS_STORE file was added.  Then all this happened.  Exactly like described in issue 22.

When I backedup my snippets and uninstalled this extension and then reinstalled it and then pasted my backed up snippets over the defaults it worked.

**Comment by jrowny** [comment]
so it does work even when .ds_store is there?

**Comment by clouddueling** [comment]
It works like this.
![screen shot 2013-10-31 at 1 04 30 pm](https://f.cloud.github.com/assets/1400735/1449355/b0ea16a6-4267-11e3-8c55-1c23ead276e6.png)

Once I start editing the json or snippet files and Mac adds .DS_STORE it breaks.  Then when I delete the .DS_STORE files and reload brackets quickly this extension works, but mac adds those back in seconds after.

**Comment by jrowny** [comment]
okay, so it's still an issue that needs to be resolved but at least we have
a temporary workaround.

On Thu, Oct 31, 2013 at 4:05 PM, CloudDueling.com
notifications@github.comwrote:

> It works like this.
> [image: screen shot 2013-10-31 at 1 04 30 pm]https://f.cloud.github.com/assets/1400735/1449355/b0ea16a6-4267-11e3-8c55-1c23ead276e6.png
> 
> Once I start editing the json or snippet files and Mac adds .DS_STORE it
> breaks. Then when I delete the .DS_STORE files and reload brackets quickly
> this extension works, but mac adds those back in seconds after.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jrowny/brackets-snippets/issues/11#issuecomment-27522725
> .

## 

Jonathan

**Comment by chrismatheson** [comment]
Hey, sorry my 'fix' was more a hack. Mac adds a .DS_Store to any folder viewed by Finder (I think) it's something to do with the images generated for quick look.

I'm happy to look at this again some time this week if we can hammer out the exact problem?

**Comment by jrowny** [comment]
So Brackets is getting a big upgrade to its filesystem in Sprint 34 (current sprint) so I plan on tackling this fix along with the filesystem.

**Comment by jrowny** [comment]
https://github.com/adobe/brackets/wiki/File-System-API-Migration info about the file system change

**Comment by clouddueling** [comment]
Ok for some reason I am not getting updates about the most recent pull requests.  I just checked main.js and compared to my local and they were not the same.  I didn't see a "Update" next to the extension in brackets.

Just to confirm this is working now for my mac :+1:

**Comment by jayeshcp** [comment]
Has this issue been fixed?

**Comment by jrowny** [comment]
@jayeshcp yes but it hasn't been put in the registry yet. That will happen this week.
