### ISSUE TITLE
No snippets showing, no error either

### ISSUE THREAD

**Issue by cfjedimaster** [jrowny/brackets-snippets#17]
I just updated my copy of the extension and I'm not getting any snippets showing up. The panel displays, but nothing is listed. No errors show up in DevTools either. I did add my own file (https://gist.github.com/cfjedimaster/5990893), but this was working for me in the past, and again, I assume if it was broken I'd see an error.

**Comment by cfjedimaster** [comment]
I'm digging, but I think I may know what it is. A long time ago I made a symbolic link for my brackets extensions so I could store them on Dropbox and share them for many machines. I added a console.log to see what directory Snippets thinks it should use for snippets. It reports:

/Users/ray/Library/Application Support/Brackets/extensions/user/brackets-snippets/data 

Which is right, but not the real one.

**Comment by cfjedimaster** [comment]
Although - the fail event should have fired if it couldn't parse it. Still digging.

**Comment by cfjedimaster** [comment]
Ok, I see the issue. Your code here:

```
                                if (entries[i].name.charAt(0) === ".") {
                                    //ignore dotfiles
                                    return
                                }
```

This causes Brackets to ignore the _entire_ directory, not just the file.

**Comment by jrowny** [comment]
I don't have a mac or silly dot files in my folders so I didn't run into this, but thanks for narrowing the issue and the pull request!
