### ISSUE TITLE
Consider XML as a snippet format

### ISSUE THREAD

**Issue by cfjedimaster** [jrowny/brackets-snippets#2]
One issue I have with the JSON syntax and snippets is that it is difficult to create large, multi-line snippets. I normally create a lot of snippets that are basically page templates. In order to get these working, I had to write a quick app to JSON encode my large strings. That took all of about 2 minutes, but what if the extension allow you to use XML files as well. Something along the lines of:

```
<snippets>
<snippet name="Foo">
<usage>..</usage>
<description>...</description>
<template> cdata block here</template>
</snippet>
```

**Comment by jrowny** [comment]
this would be a great feature to add. For the time being, there's a lot of automated tools to escape your snippets to work with JSON.

**Comment by cfjedimaster** [comment]
Yeah, but it also makes it hard to update too. So for example, one page template may have a call to jQuery 1.4.1, and if I want to modify that, it may be more difficult with encoded for JSON. (Probably not, but I'm reaching here. ;) Mind if I code this up and submit a pull request?

**Comment by jrowny** [comment]
I agree with you, so go for it!

**Comment by jrowny** [comment]
So I think I resolved this by allowing you to specify an external file as the snippet.

`{
        "name": "html5",
        "trigger": "html5",
        "usage": "html5",
        "description": "Create an HTML5 page",
        "template": "html5.snippet"
}`

html5.snippet is a file in your directory which is basically just HTML.

**Comment by cfjedimaster** [comment]
Perfect. Thanks!
