### ISSUE TITLE
Finding Snippets javascript.json File

### ISSUE THREAD

**Issue by martypowell** [jrowny/brackets-snippets#21]
This is more of a comment then issue. I am new to brackets as of yesterday and was having a hard time finding the javascript.json.  

I had to do quite a bit of googling before finding this blog article (http://blog.brackets.io/2012/12/19/snippets-brackets-extension/) that mentions accessing “Show Extensions Folder” in the Help menu.

It might be nice to add this little tip into the adding snippets section.

Great extension, thank you!

**Comment by jrowny** [comment]
It wasn't really the intention to have user snippets in that folder but I haven't really come up with a better way. We do have config.js which lets you customize the extension path but that gets overwritten when the module updates. I probably need to move that into a settings UI and make it persist.

**Comment by raphaelbastide** [comment]
+1
At least shortcut to the snippets folder in Brackets UI could be really useful.

**Comment by zaggino** [comment]
Settings UI is available in https://github.com/jrowny/brackets-snippets/pull/34

**Comment by martypowell** [comment]
Awesome, thank you!

**Comment by zaggino** [comment]
@martypowell This is not solved yet, I'll do it once #34 will be merged by @jrowny

**Comment by zaggino** [comment]
Solved in https://github.com/jrowny/brackets-snippets/pull/36
