### ISSUE TITLE
snippets folder

### ISSUE THREAD

**Issue by benoitwimart** [jrowny/brackets-snippets#22]
Hi,

After add my own ".snippet" file, Mac OS X add a ".DS_Store" file and brackets-snippets doesn't start.
I used this command to remove this hidden file and fix it :
cd Users/…/Library/Application\ Support/Brackets/extensions/user/jrowny.brackets.snippets/data/snippets

sudo rm ".DS_Store"

B.

**Comment by jrowny** [comment]
I'm closing this because it's a duplicate of issue #11. Please track #11 for progress on fixing this.
