### ISSUE TITLE
Incorrect file IO error messages

### ISSUE THREAD

**Issue by peterflynn** [jrowny/brackets-snippets#25]
There are two places this extension does: `FileUtils.showFileOpenError(error.code, path)`, but there is no "error.code" field so it will always show a generic message with "undefined" given as the error type.

There's one place where it does: `FileUtils.showFileOpenError(error.name, path)`, which is correct in Sprint 33 and earlier, but will stop working in Sprint 34.  The correct code for Sprint 34+ is `FileUtils.showFileOpenError(error, path)`.

It should be possible to use something like `FileUtils.showFileOpenError(error.name || error, path)` to be compatible with all versions.

See [this discussion thread](https://groups.google.com/forum/#!topic/brackets-dev/95PyDKfMO0M) for more background on the Sprint 34 filesystem API changes.

**Comment by peterflynn** [comment]
There are also several uses of deprecated APIs in this extension:
- `NativeFileSystem.FileEntry`
- `NativeFileSystem.requestNativeFileSystem()`
- `DirectoryEntry.createReader()`

These APIs _should_ continue to work in Brackets Sprint 34, so you do not necessarily need to clean them up at the same time as fixing the breaking changes above.  But the APIs will go away by the end of this year, so you should migrate away from them as soon as you have time (see same [migration guide](https://github.com/adobe/brackets/wiki/File-System-API-Migration) as above).

Let me know if you want me to spin that off as a separate issue or anything.

**Comment by zaggino** [comment]
Solved in https://github.com/jrowny/brackets-snippets/pull/36

**Comment by peterflynn** [comment]
Cool, thanks!
