### ISSUE TITLE
Created a gif on this extension

### ISSUE THREAD

**Issue by clouddueling** [jrowny/brackets-snippets#26]
https://dl.dropboxusercontent.com/u/7827818/brackets%20snippets.gif

I created this gif for a quick preview on my site: http://michaelcalkins.com/post/brackets-snippets-extension

If you want the file go for just thought I'd offer it up :)

If you want to make an easy one yourself google LICEcap it's free and super easy to use.

**Comment by jrowny** [comment]
thanks!
