### ISSUE TITLE
Dynamic n variables

### ISSUE THREAD

**Issue by adalberth** [jrowny/brackets-snippets#27]
I wanna create a console.log snippet: console.log($${data}); and i would like to be able to pass multi variables like: cl myVar1, myVar2 .. myVarN. Is that somehow possible? and another small problem is that you can only use the !!{cursor} placeholder with /n!!{cursor}/n or else it doesn't work.

**Comment by jrowny** [comment]
This is now fixed with pull request #31 and #33 by putting the params in a string and using the 1 line snippet.
