### ISSUE TITLE
Snippets GIF Example

### ISSUE THREAD

**Issue by clouddueling** [jrowny/brackets-snippets#29]
Hope this can be helpful!

I recommend downloading it because this link will die someday.
https://dl.dropboxusercontent.com/u/7827818/brackets%20snippets%20example.gif
http://michaelcalkins.com/post/69376921361/programming-quickly-with-brackets

<img src='https://dl.dropboxusercontent.com/u/7827818/brackets%20snippets%20example.gif'>

**Comment by Semigradsky** [comment]
Looks cool.
How about add this to readme?

**Comment by zaggino** [comment]
Present in #38
