### ISSUE TITLE
Error in Sprint 17

### ISSUE THREAD

**Issue by cfjedimaster** [jrowny/brackets-snippets#3]
Uncaught TypeError: Cannot call method 'createReader' of undefined 

at

file:///C:/Users/Raymond/AppData/Roaming/Brackets/extensions/user/brackets-snippets/main.js

**Comment by jrowny** [comment]
I created a tag because my updates broke Sprint 17. 

You can resolve this issue by getting the latest master or getting the tag: https://github.com/jrowny/brackets-snippets/tags

**Comment by jrowny** [comment]
To clarify, if you've got a copy of Brackets on master, it should work and there are a few other things cleaned up.

**Comment by cfjedimaster** [comment]
Ah cool - and I think I remember that email from a few days ago about a
change that would break extensions.

On Tue, Dec 18, 2012 at 2:07 PM, Jonathan notifications@github.com wrote:

> To clarify, if you've got a copy of Brackets on master, it should work and
> there are a few other things cleaned up.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jrowny/brackets-snippets/issues/3#issuecomment-11502842.

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by jrowny** [comment]
I added a note in the readme.
