### ISSUE TITLE
Using jQuery code in InlineSnippetForm.js?

### ISSUE THREAD

**Issue by ghost** [jrowny/brackets-snippets#4]
Hi, i am new to github and brackets and i was doing some simple tests with the Snippets extension and trying some simple customizations but i have run into a problem where my jQuery code does not work. 

In the browser this code works fine -

<body>

```
<div style="padding-bottom:4px;"/>
    <input type="text" class="testing" id="testing"/>
</div>
<script>
    $('#testing').hide();
</script>

</body>
```

But in the InlineSnippetForm.js file after the line -

```
$element.append('<input type="text" class="snipvar-' + property + '"/>');
```

I add this code -

```
$element.append('<input type="text" class="testing" id="testing"/>');

$('#testing').hide();
```

However everytime i run the snippet i see 2 text inputs rather than just 1 like i was expecting (with 1 hidden).

Am i selecting the text input the wrong way or is there some sort of gui refreshing code needed before a visual update is seen? Many thanks

**Comment by jrowny** [comment]
Could be a conflict somewhere with the id "testing". Try something like:

```
$testing = $('<input type="text"/>');
$element.append($testing);
$testing.hide();
```

If you've got dev tools open (F12 on windows, cmd+shift+i on mac) you can console `console.log($('#testing'))` and see what it's giving you.

As this is a general javascript/jQuery problem and not so much related to a specific contribution or bug in Brackets or the snippets extension, I'm going to close this. If you've got more questions feel free to find me on IRC.

**Comment by ghost** [comment]
Thanks that fixed the problem :)
