### ISSUE TITLE
snippets suggest like sublime text

### ISSUE THREAD

**Issue by mrroot5** [jrowny/brackets-snippets#40]
Hello!

This is my first post here, I am a noob. If I do something wrong, I am sorry :). If the issue is created I didn't find it.

I can't see a snippet suggest when I wrote a snippet. To insert the snippet it only works Ctrl-Alt-Space? What I want is that when I type the snippet name it appears the suggets snippets list while I am writing, so I can choose the one I want.

Like Sublime Text :).

**Comment by zaggino** [comment]
This feature is not available yet but it's a very good suggestion.

**Comment by mrroot5** [comment]
Ok, I wait for it :). Thank you for reply :).

**Comment by zaggino** [comment]
You can leave it open as a feature suggestion.

**Comment by mrroot5** [comment]
Ok, sorry, I am a noob in this situation :s.

**Comment by zaggino** [comment]
@erknrio this has been implemented in my fork here https://github.com/zaggino/brackets-snippets

**Comment by mrroot5** [comment]
Hello @zaggino, great news! but in brackets I can't update the brackets snippets plugin :S. I try to install your fork by URL but I have an installation error.

**Comment by zaggino** [comment]
The fork is not 100% ready and stable, I'm implementing other things with it and removing some I find not required anymore. When I'll be happy with it, then I'll release it to the Brackets registry. You can install it by manually if you wish for now, see here https://github.com/adobe/brackets/wiki/Brackets-Extensions#directly-on-disk ... you just extract the files from github into the extensions folder.

**Comment by mrroot5** [comment]
Ok, perfect. I prefer to wait for the last version. Thanks for your work :).
