### ISSUE TITLE
Not working - Brackets sprint 38 on Mac

### ISSUE THREAD

**Issue by kpgarrod** [jrowny/brackets-snippets#41]
I have installed the extension but can't get it to work. It seems that Cmd-Shift-S is assigned to 'save as' and Alt-Cmd-V doesn't do anything. What am I missing here?

**Comment by zaggino** [comment]
hi @kpgarrod 
the default shortcut was actually changed to Ctrl-Alt-Space (cmd-alt-space on mac?)
you can define your own shortcut when you open the snippets panel and click on settings there

**Comment by kpgarrod** [comment]
hi @zaggino 
thanks for the quick response, but how do I open the snippets panel?

**Comment by zaggino** [comment]
there should be icon on the right side of the brackets with letter "S"

**Comment by kpgarrod** [comment]
and so there is, thanks! I did have to change the shortcut on my mac to make it work - Shift-Tab worked for me.

**Comment by zaggino** [comment]
:+1:
