### ISSUE TITLE
Improve documentation about custom keyboard shortcuts

### ISSUE THREAD

**Issue by glepretre** [jrowny/brackets-snippets#48]
Hello,

I would like to change the default keyboard shortcut to insert a snippet but I don't know which are the accepted keys and the naming convention used.

Can we use arrows, numpad, `Super` ? Specify left or right `Shift` ?

I think it would be useful to add this to README or a specific doc :smiley:

Thanks.

**Comment by zaggino** [comment]
@glepretre format is the same as Brackets format for shortcuts, see this file for example: https://github.com/adobe/brackets/blob/master/src/base-config/keyboard.json

**Comment by glepretre** [comment]
Thank you,

This answers some questions but what about numpad keys, Super (on Windows or Linux) and key location : left or right?

Would you accept a PR to document that?

**Comment by zaggino** [comment]
We can leave it open but I don't have the time to dedicate into this right now.
