### ISSUE TITLE
Fairly serious bug with brackets after using the Snippets plugin

### ISSUE THREAD

**Issue by ghost** [jrowny/brackets-snippets#5]
I have found a fairly serious bug with the Snippets plugin (Great plugin btw) where Brackets becomes hard to use when clicking with the mouse.

---

You should be able to reproduce the bug with the following steps -

1) With the plugin enabled load brackets and have a page with quite a lot of content like the default index.html which was the document i found this bug with.

2) Scroll down the page and click on line 62 (Could be another but it's what i use for this step)

3) Scroll up to the very top of the page again

4) Bring up the Snippets panel using the Ctrl-Shift-S shortcut (Using the menu probably makes no difference) 

5) Click the "link" snippet (Or any snippet with input parameters)

6) Optionally type some text and insert with the button or enter key

7) Now click a line that is visible just above the Snippets dialog (On my monitor it's about line 94)

8) You should have now triggered the bug

---

What the bug seems to do is start selecting multiple lines of text with single mouse clicks as if you were clicking and dragging to select text. This makes the program very difficult to keep using so i then need to close Brackets to continue working after this starts happening.

Additionally with the steps to make the bug trigger it seems you can swap steps 3 and 4 around. Also when testing i found once the bug is triggered it's when your clicking downwards/lower half in the window and going upwards/top half seems to move the cursor/line position as normal.

---

Also a off-topic feature request for the Snippets plugin would be to allow vertical resizing of the Snippets panel so you can see more than 5 snippets at a time.

**Comment by jrowny** [comment]
I think this is fixed in the latest commit, as well as the panel resizing. Let me know if yous till experience any trouble.
