### ISSUE TITLE
Feature Request: make bottom panel resizable

### ISSUE THREAD

**Issue by redmunds** [jrowny/brackets-snippets#6]
There is now a resizer module that implements easy resizing of bottom panels. You don't need any JS -- just add a few classes to your HTML markup.

Take a look at the Brackets JSLint and Find in Files panels, or this extension I wrote: https://github.com/redmunds/brackets-display-shortcuts.

**Comment by jrowny** [comment]
Opps, I finally got around to this and now apparently we're using PanelManager.createBottomPanel().

**Comment by jrowny** [comment]
Fixed in latest commit
