### ISSUE TITLE
Feature Request: add foreach loop

### ISSUE THREAD

**Issue by redmunds** [jrowny/brackets-snippets#7]
A for loop is useful for when there are cases you want to break out of loop, but foreach is much cleaner when you know you're going to loop through entire list. So, instead of this:

```
var x;
for (x = 0; x < someArray.length; x++) {

}
```

I'd rather start with this:

```
itemList.foreach(function (item) {

});
```

**Comment by jrowny** [comment]
I don't think the looping debate is something I really want to cover with this module. I `for` as often as I `foreach` for various reasons. I will go ahead and add a `foreach` starting snippet but leave the original in place.

**Comment by redmunds** [comment]
I guess my "I'd rather..." comment was confusing. I definitely think there should be both.

**Comment by jrowny** [comment]
done.
