### ISSUE TITLE
Needs a new line to trigger

### ISSUE THREAD

**Issue by choyan** [jrowny/brackets-snippets#8]
May be you know it.
Snippets doesn't appear without creating a newline. I need to go to a new line or press enter. Then when i insert a  trigger then, snippet works. May be everybody wont want it. People needs to add a comment just side of the end of tag.

English is too bad. Hope so, you understand my words, :)

**Comment by jrowny** [comment]
Right now the snippets rely on creating new lines because of the way the parameters work. Otherwise it would be very difficult to parse the snippet from the line. If you have ideas about how I can address this, let me know. For now I will close as won't fix.
